# Generated by Django 6.0.4 on 2026-06-26 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_servicio_duracion_alter_servicio_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='core.servicio'),
        ),
    ]
